GET http://localhost:5002/offers?limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJCYXllcjIiLCJ1c2VySWQiOjMsInJvbGUiOiJjdXN0b21lciIsImxhc3ROYW1lIjoiQmF5ZXJvdnljaDIiLCJhdmF0YXIiOiJhbm9uLnBuZyIsImRpc3BsYXlOYW1lIjoiYnV5ZXJkbjIiLCJiYWxhbmNlIjoiMCIsImVtYWlsIjoiYnV5ZXJkbjJAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3MzE4NjE2MDAsImV4cCI6MTczMTg2NTIwMH0.21SLzPgdcDds4SCPT12VtUDRfuc8L-0hgam5JRXr3p4